#- include: redmine_absolute_dates.yml
#- include: redmine_wiki_extensions.yml 
# 3.4 incompatible now - include: redmine_scm.yml
- include: redmine_startpage.yml
- include: redmine_issue_templates.yml
- include: redmine_banner.yml
- include: redmine_view_customize.yml
#- include: redmine_wiki_lists.yml
#- include: redmine_work_time.yml
- include: redmine_xlsx_format_issue_exporter.yml
#- include: redmine_pivot_table.yml
#- include: redmine_full_text_search.yml
- include: redmine_theme_changer.yml
#- include: redmine_mermaid_macro.yml
#- include: redmine_wysiwyg_editor.yml
#- include: redmine_tags.yml
- include: redmine_default_custom_query.yml
- include: redmine_message_customize.yml

- name: bundle install
  become: yes
  command:
    bundle install
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: db migration
  become: yes
  command:
    bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: Restart redmine
  become: yes
  service: name=apache2 state=restarted
